name: makelint

on: 
  - push

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - run: npm install
        run: 
          make install
      - name: run lint
        run: 
          make lint